ARG DOCKERSRC=frommakefile
#
FROM ${DOCKERSRC}
#
ARG PUID=1001
ARG PGID=1001
ARG JVVMAJOR=8
ENV LANG=C.UTF-8
#
RUN addgroup -g ${PGID} -S alpine && \
    adduser -u ${PUID} -G alpine -h /home/alpine -D alpine
#
RUN set -xe \
    && (if [ ${JVVMAJOR} -lt 9 ]; \
    then \
        apk add -uU --no-cache \
            curl \
            ca-certificates \
            nss \
            openjdk${JVVMAJOR}-jre-base; \
    else \
        apk add -uU --no-cache \
            --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
            curl \
            ca-certificates \
            nss \
            openjdk${JVVMAJOR}-jre-headless; \
    fi;) \
    && rm -rf /var/cache/apk/* /tmp/*
#
ENV JAVA_HOME /usr/lib/jvm/java-1.${JVVMAJOR}-openjdk
# ENTRYPOINT ["/init"]
# ENTRYPOINT ["/usr/bin/java"]
